/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as UsageIndexRouteImport } from './app/usage/index'
import { Route as TasksIndexRouteImport } from './app/tasks/index'
import { Route as SkillsIndexRouteImport } from './app/skills/index'
import { Route as SessionsIndexRouteImport } from './app/sessions/index'
import { Route as MemoryIndexRouteImport } from './app/memory/index'
import { Route as CronjobsIndexRouteImport } from './app/cronjobs/index'
import { Route as SessionsSessionIdRouteImport } from './app/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageIndexRoute = UsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIndexRoute = MemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CronjobsIndexRoute = CronjobsIndexRouteImport.update({
  id: '/cronjobs/',
  path: '/cronjobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/cronjobs/': typeof CronjobsIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/usage/': typeof UsageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/cronjobs': typeof CronjobsIndexRoute
  '/memory': typeof MemoryIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/usage': typeof UsageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/cronjobs/': typeof CronjobsIndexRoute
  '/memory/': typeof MemoryIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/usage/': typeof UsageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sessions/$sessionId'
    | '/cronjobs/'
    | '/memory/'
    | '/sessions/'
    | '/skills/'
    | '/tasks/'
    | '/usage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sessions/$sessionId'
    | '/cronjobs'
    | '/memory'
    | '/sessions'
    | '/skills'
    | '/tasks'
    | '/usage'
  id:
    | '__root__'
    | '/'
    | '/sessions/$sessionId'
    | '/cronjobs/'
    | '/memory/'
    | '/sessions/'
    | '/skills/'
    | '/tasks/'
    | '/usage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  CronjobsIndexRoute: typeof CronjobsIndexRoute
  MemoryIndexRoute: typeof MemoryIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  UsageIndexRoute: typeof UsageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage/': {
      id: '/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof UsageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/': {
      id: '/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof MemoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronjobs/': {
      id: '/cronjobs/'
      path: '/cronjobs'
      fullPath: '/cronjobs/'
      preLoaderRoute: typeof CronjobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  CronjobsIndexRoute: CronjobsIndexRoute,
  MemoryIndexRoute: MemoryIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  UsageIndexRoute: UsageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
